language: python
env: HASS='homeassistant==0.54'  #Change to your version from .HA_VERSION
python:
  - "3.4"
matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: HASS='homeassistant'
    - python: "3.4"
      env: HASS='https://github.com/home-assistant/home-assistant/archive/dev.zip'
  allow_failures:
    - python: "3.4"
      env: HASS='homeassistant'
    - python: "3.4"
      env: HASS='https://github.com/home-assistant/home-assistant/archive/dev.zip'
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install $HASS
  - hass --version
script:
  - hass -c . --script check_config
