homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 711
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customizations/customize
  customize_domain: !include_dir_merge_named customizations/customize_domain
  customize_glob: !include_dir_merge_named customizations/customize_glob

frontend:
http:
  #base_url: !secret base_url
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
discovery:
conversation:
#history:
#logbook:
sun:
updater:
config:

#recorder:
#  db_url: !secret database_url

ios:

zwave:
  usb_path: /dev/ttyACM0

alert: !include_dir_named alerts
automation: !include_dir_list automations
binary_sensor: !include_dir_merge_list binary_sensors
device_tracker: !include_dir_merge_list trackers
emulated_hue: !include hubs/emulated_hue_bridge.yaml
group: !include_dir_named groups
input_boolean: !include_dir_named inputs/booleans
input_number: !include_dir_named inputs/numbers
light: !include_dir_merge_list lights
media_player: !include_dir_merge_list media_players
mqtt: !include servers/mqtt.yaml
notify: !include_dir_merge_list notifiers
panel_iframe: !include_dir_named iframes
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
shell_command: !include commands/shell_commands.yaml
switch: !include_dir_merge_list switches/
zone: !include_dir_merge_list zones
