homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 711
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customizations

frontend:
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
discovery:
conversation:
history:
logbook:
sun:
updater:

automation: !include_dir_list automations
device_tracker: !include_dir_merge_list trackers
group: !include_dir_named groups
input_select: !include_dir_named inputs/selects
input_boolean: !include_dir_named inputs/booleans
mqtt: !include servers/mqtt.yaml
notify: !include_dir_merge_list notifiers
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
shell_command: !include commands/shell_commands.yaml
zone: !include_dir_merge_list zones
