########################################
#         Personal Information         #
########################################

########################################
#            Home Assistant            #
########################################
base_url: example.com
http_password: password
latitude: 0
longitude: 0
time_zone: 0
home_address: 0
static_ip: 0
internal_ip: 0
ssl_certificate: 0
ssl_key: 0

# Iframes
graph_url: example.com

########################################
#              Notifiers               #
########################################
pushbullet_api_key: 0
pushbullet_krasi_email: 0
pushbullet_ida_email: 0

gmail_sender: 0
gmail_username: 0
gmail_password: 0
gmail_recipient: 0

########################################
#                 MQTT                 #
########################################
mqtt_username: 0
mqtt_password: 0

########################################
#                 Router               #
########################################
tplink_username: 0
tplink_password: 0
tplink_ip_address: 0

########################################
#                Sensors               #
########################################
google_time_travel_api_key: 0

sensors:
- platform: template
  sensors:
    ipchange:
      entity_id: sensor.external_ip
      value_template: "{%- if is_state('sensor.external_ip', '0') -%} False {%- else -%} True {%- endif %}"
