alias: Turn on staircase led lights on home entering
trigger:
  - platform: state
    entity_id: device_tracker.pi_krasi_phone, device_tracker.pi_ida_phone
    from: 'not_home'
    to: 'home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sensor.staircase_state
      state: 'off'
    - condition: sun
      after: sunset
action:
  - service: script.staircase_led_on
