alias: Turn staircase led light on
trigger:
  platform: state
  entity_id: input_boolean.staircase_led_state
  state: 'on'     
action:
  service: notify.staircase_led
  data:
    message: '{ "workMode" : "on" }'
