alias: Turn staircase led light off
trigger:
  platform: state
  entity_id: input_boolean.staircase_led_state
  state: 'off'
action:
  service: notify.staircase_led
  data:
    message: '{ "workMode" : "off" }'
