alias: Set staircase led options
trigger:
- platform: state
  entity_id: input_select.staircase_led_animation_mode, input_select.staircase_led_color, input_select.staircase_led_direction
action:
  service: notify.staircase_led
  data:
    message: '{ "animationMode" : "{{states("input_select.staircase_led_animation_mode")}}", "color" : "{{states("input_select.staircase_led_color")}}", "direction" : "{{states("input_select.staircase_led_direction")}}" }'
