alias: Turn on the kitchen led after sunset
trigger:
  platform: sun
  event: sunset
condition:
  condition: time
  before: '00:00:00'
action:
  service: homeassistant.turn_on
  entity_id: switch.kitchen
