alias: Send notification when Ida gets home
trigger:
  platform: state
  entity_id: device_tracker.pi_ida_phone
  from: 'not_home'
  to: 'home'
action:
  service: notify.pushbullet
  data_template:
    message: Ida is at home.
    target: !secret pushbullet_krasi_email
