- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_free
    - type: last_boot
    - type: disk_use_percent
      arg: /

- platform: rest
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'
