- platform: forecast
  api_key: a4277fdc3bfc990a0e8b00f73f1a7d34
  monitored_conditions:
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - humidity
    - daily_summary
