- platform: darksky
  api_key: !secret dark_sky_api_key
  monitored_conditions:
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - humidity
    - daily_summary
