- platform: template
  sensors:
    low_battery_krasi_phone:
      value_template: '{{ states.device_tracker.pi_krasi_phone.attributes.battery < 20 }}'
    low_battery_ida_phone:
      value_template: '{{ states.device_tracker.pi_ida_phone.attributes.battery < 20 }}'

