alias: Turn staircase led light on
trigger:
  platform: state
  entity_id: input_boolean.staircase_led_state
  to: 'on'
condition:
  condition: state
  entity_id: sensor.staircase_state
  state: 'off'
action:
  service: notify.staircase_led
  data:
    message: '{ "workMode" : "on" }'
