alias: Disk usage
trigger:
  platform: numeric_state
  entity_id: sensor.disk_use_
  above: 80
action:
  - service: persistent_notification.create
    data:
      title: 'Hard Drive Monitor:'
      message: 'Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_.state }}%!'
      notification_id: 'Critical Alert'
  - service: notify.krasi_pushbullet
    data_template:
      title: 'Hard Drive Monitor:'
      message: 'Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_.state }}%!'

