alias: New device connected
trigger:
  platform: event
  event_type: device_tracker_new_device
action:
  - service: persistent_notification.create
    data:
      title: 'New device connected:'
      message: 'There has been a new device detected on the network. Be sure to appropriately catagorize it within Circle.'
      notification_id: 'Critical Alert'
  - service: notify.pushbullet
    data_template:
      title: 'New device connected:'
      message: 'There has been a new device detected on the network. Be sure to appropriately catagorize it within Circle.'
      target: !secret pushbullet_krasi_email
