alias: Notify if IP changes
trigger:
  platform: state
  entity_id: sensor.ipchange
  from: 'False'
  to: 'True'
action:
  - service: persistent_notification.create
    data:
      title: 'Changed IP address:'
      message: 'New IP: {{ states.sensor.external_ip.state }}'
      notification_id: 'Critical Alert'
  - service: notify.krasi_pushbullet
    data:
      title: 'Changed IP address:'
      message: 'New IP: {{ states.sensor.external_ip.state }}'

