alias: Turn on the kitchen light on motion
trigger:
  platform: state
  entity_id: binary_sensor.motion_sensor_158d000227081e
  to: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.kitchen
      white_value : 225
  - service: homeassistant.turn_on
    entity_id: light.kitchen_ornamental_led
