alias: Turn off the kitchen light 2 minutes after last movement
trigger:
  platform: state
  entity_id: binary_sensor.motion_sensor_158d000227081e
  to: 'off'
action:
  - service: homeassistant.turn_off
    entity_id: light.kitchen
  - service: homeassistant.turn_off
    entity_id: light.kitchen_ornamental_led
