alias: Turn on some of the lights upon home entering
trigger:
  - platform: state
    entity_id: device_tracker.pi_krasi_phone, device_tracker.pi_ida_phone
    from: 'not_home'
    to: 'home'
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunset
action:
  - service: script.staircase_led_on
  - service: homeassistant.turn_on
    entity_id: light.kitchen_ornamental_led
