alias: Home Assistant start up automation
hide_entity: True
trigger:
  platform: event
  event_type: homeassistant_start
action:
  service: automation.trigger
  entity_id: automation.update_staircase_toggle_switch

