alias: Send email when home state to home
trigger:
  platform: state
  entity_id: device_tracker.pi_krasi_phone
  from: 'not_home'
  to: 'home'
action:
- service: notify.email
  data:
    title: 'home'
    message: 'enter'
