alias: Send email when home state change to not_home
trigger:
  platform: state
  entity_id: device_tracker.pi_krasi_phone
  from: 'home'
  to: 'not_home'
action:
- service: notify.email
  data:
    title: 'home'
    message: 'leave'
