alias: Set staircase led color
trigger:
- platform: state
  entity_id: input_select.staircase_work_mode
- platform: state
  entity_id: input_select.staircase_animation_mode
- platform: state
  entity_id: input_select.staircase_led_color
action:
  service: templated_shell_command.staircase_set
