alias: Turn on staircase led lights when there is #TODO
trigger:
  - platform: state
    entity_id: device_tracker.pi_krasi_phone
    from: 'not_home'
    to: 'home'
#  - platform: sun
#    event: sunset
action:
  service: script.staircase_led_on
